services:
  db_orders:
    image: postgis/postgis:18-3.6-alpine
    environment:
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      POSTGRES_DB: orders_db
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - wellness_kit_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  db_admins:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${ADMIN_DB_USER}
      POSTGRES_PASSWORD: ${ADMIN_DB_PASSWORD}
      POSTGRES_DB: admins_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_admins:/var/lib/postgresql/data
    networks:
      - wellness_kit_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AllowedHosts=${ALLOWED_HOSTS}
      - Cors__AllowedOrigins__0=${CORS_ALLOWED_ORIGINS_0}
      - Cors__AllowedOrigins__1=${CORS_ALLOWED_ORIGINS_1}
      - Jwt__Key=${JWT_KEY}
      - DefaultAdmin__Username=${DEFAULT_ADMIN_USER}
      - DefaultAdmin__Password=${DEFAULT_ADMIN_PASSWORD}
      - ConnectionStrings__OrdersConnection=Host=db_orders;Port=5432;Database=orders_db;Username=${ORDER_DB_USER};Password=${ORDER_DB_PASSWORD}
      - ConnectionStrings__AdminsConnection=Host=db_admins;Port=5432;Database=admins_db;Username=${ADMIN_DB_USER};Password=${ADMIN_DB_PASSWORD}
    depends_on:
      db_orders:
        condition: service_healthy
      db_admins:
        condition: service_healthy
    networks:
      - wellness_kit_network

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - wellness_kit_network

volumes:
  pgdata:
  pgdata_admins:

networks:
  wellness_kit_network:
    driver: bridge