// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestTaskINT20H.Infrastructure.Persistence;

#nullable disable

namespace TestTaskINT20H.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestTaskINT20H.Domain.Orders.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("TestTaskINT20H.Domain.Orders.Entities.Order", b =>
                {
                    b.OwnsOne("TestTaskINT20H.Domain.Orders.ValueObjects.Money", "Subtotal", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("subtotal_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("subtotal_currency");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("TestTaskINT20H.Domain.Orders.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.Property<Point>("point")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("geometry(Point,4326)")
                                .HasColumnName("point")
                                .HasComputedColumnSql("ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)", true);

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("TestTaskINT20H.Domain.Orders.ValueObjects.TaxCalculation", "TaxCalculation", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Jurisdictions")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("jurisdictions");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("TestTaskINT20H.Domain.Orders.ValueObjects.TaxBreakdown", "Breakdown", b2 =>
                                {
                                    b2.Property<Guid>("TaxCalculationOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("CityRate")
                                        .HasColumnType("numeric(8,6)")
                                        .HasColumnName("city_rate");

                                    b2.Property<decimal>("CountyRate")
                                        .HasColumnType("numeric(8,6)")
                                        .HasColumnName("county_rate");

                                    b2.Property<decimal>("SpecialRates")
                                        .HasColumnType("numeric(8,6)")
                                        .HasColumnName("special_rates");

                                    b2.Property<decimal>("StateRate")
                                        .HasColumnType("numeric(8,6)")
                                        .HasColumnName("state_rate");

                                    b2.HasKey("TaxCalculationOrderId");

                                    b2.ToTable("orders");

                                    b2.WithOwner()
                                        .HasForeignKey("TaxCalculationOrderId");
                                });

                            b1.OwnsOne("TestTaskINT20H.Domain.Orders.ValueObjects.Money", "TaxAmount", b2 =>
                                {
                                    b2.Property<Guid>("TaxCalculationOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("tax_currency");

                                    b2.HasKey("TaxCalculationOrderId");

                                    b2.ToTable("orders");

                                    b2.WithOwner()
                                        .HasForeignKey("TaxCalculationOrderId");
                                });

                            b1.Navigation("Breakdown")
                                .IsRequired();

                            b1.Navigation("TaxAmount")
                                .IsRequired();
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Subtotal")
                        .IsRequired();

                    b.Navigation("TaxCalculation");
                });
#pragma warning restore 612, 618
        }
    }
}
